language: csharp
solution: src/Reko-decompiler.sln
install:
  - nuget restore src/Reko-decompiler.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - sh ./setup.sh -u
  - msbuild /version
  - msbuild /p:Configuration=TravisRelease src/Reko-decompiler.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/tools/c2xml/bin/TravisRelease/c2xml.exe -exclude=UserInterface,FailedTests
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/UnitTests/bin/x86/TravisRelease/Reko.UnitTests.dll -exclude=UserInterface,FailedTests
  - python ./subjects/regressionTests.py --check-output --configuration=TravisRelease
